services:
  db:
    container_name: monitoring-app-database
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
    - ${DB_PORT}:${DB_PORT}

  redis:
    container_name: monitoring-app-broker
    image: redis:alpine3.18
    restart: on-failure
    ports:
      - ${BROKER_PORT}:${BROKER_PORT}